from django.shortcuts import render
from .models import *

def main(request):
    return render(request, 'leaf/templates/main.html', {})


def showDatalist(request):
    cafes = Cafe.objects.all()
    return render(request, 'leaf/templates/show_data_list.html', {'cafes': cafes})

def user_data(request):
     user[0] = User.objects.create(id=id, user_id='gkfka5968',password='fhwm0406',name='김하람',is_staff='True',tag_search='',cafe_id='')
     user[1] = User.objects.create(id=id, user_id='anchovy582', password='mFe9#i!AF', name='정진우', is_staff='True', tag_search='', cafe_id='')
     user[2] = User.objects.create(id=id, user_id='jjong11', password='r9RuYY!t&', name='정소희', is_staff='True', tag_search='', cafe_id='')
     user[3] = User.objects.create(id=id, user_id='jmingrove', password='Asn*h0POj', name='정민규', is_staff='True', tag_search='', cafe_id='')
     user[4] = User.objects.create(id=id, user_id='angimo53', password='O$PGM1ppb', name='전상호', is_staff='True', tag_search='', cafe_id='')
     user[5] = User.objects.create(id=id, user_id='pachai713', password='S%VNeVcL!', name='배재훈', is_staff='True', tag_search='', cafe_id='')
     user[6] = User.objects.create(id=id, user_id='master542', password='xOFnp?yQY', name='김민주', is_staff='True', tag_search='', cafe_id='')
     user[7] = User.objects.create(id=id, user_id='othe', password='SkC=V5Rj5', name='이제찬', is_staff='True', tag_search='', cafe_id='')
     user[8] = User.objects.create(id=id, user_id='larana00', password='C^QHliYkt', name='박상혁', is_staff='True', tag_search='', cafe_id='')
     user[9] = User.objects.create(id=id, user_id='pase342', password='OmlVP-aYf', name='임진희', is_staff='True', tag_search='', cafe_id='')
     user[10] = User.objects.create(id=id, user_id='agnas860', password='cHlw~fxas', name='신선', is_staff='True', tag_search='', cafe_id='')
     user[11] = User.objects.create(id=id, user_id='kiri437', password='otbV8-WEj', name='최민정', is_staff='True', tag_search='', cafe_id='')
     user[12] = User.objects.create(id=id, user_id='farma33', password='cwnvH$^r6', name='송정우', is_staff='True', tag_search='', cafe_id='')
     user[13] = User.objects.create(id=id, user_id='leth', password='qiFfU@9!N', name='조민제', is_staff='True', tag_search='', cafe_id='')
     user[14] = User.objects.create(id=id, user_id='lotak', password='La8a&~Hj4', name='정진희', is_staff='True', tag_search='', cafe_id='')
     user[15] = User.objects.create(id=id, user_id='oroda12', password='WjLcbod#4', name='권태풍', is_staff='True', tag_search='', cafe_id='')
     user[16] = User.objects.create(id=id, user_id='henni53', password='R$IM5bUM!', name='이준호', is_staff='True', tag_search='', cafe_id='')
     user[17] = User.objects.create(id=id, user_id='tumus83', password='QGt=saCrL', name='서준', is_staff='True', tag_search='', cafe_id='')
     user[18] = User.objects.create(id=id, user_id='guda643', password='RjG+Fl38i', name='소현섭', is_staff='True', tag_search='', cafe_id='')
     user[19] = User.objects.create(id=id, user_id='gilne01', password='P_@UnaMuc', name='박수린', is_staff='True', tag_search='', cafe_id='')
     user[20] = User.objects.create(id=id, user_id='lydie', password='B&Y6gKzjD', name='최윤지', is_staff='True', tag_search='', cafe_id='')
     user[21] = User.objects.create(id=id, user_id='conly', password='jOV6i*g$8', name='서재명', is_staff='True', tag_search='', cafe_id='')
     user[22] = User.objects.create(id=id, user_id='colvis', password='X3*xofwkF', name='차재명', is_staff='True', tag_search='', cafe_id='')
     user[23] = User.objects.create(id=id, user_id='celen96', password='w^a@jUJBm', name='이시훈', is_staff='True', tag_search='', cafe_id='')
     user[24] = User.objects.create(id=id, user_id='kenus', password='j@qV9~afy', name='안병준', is_staff='True', tag_search='', cafe_id='')
     user[25] = User.objects.create(id=id, user_id='sheelm', password='Z7t+xIhPD', name='조형준', is_staff='True', tag_search='', cafe_id='')
     user[26] = User.objects.create(id=id, user_id='adan55', password='ZBC&~C1bJ', name='정해선', is_staff='False', tag_search='', cafe_id='')
     user[27] = User.objects.create(id=id, user_id='stan09', password='fJb_*thkc', name='김명운', is_staff='False', tag_search='', cafe_id='')
     user[28] = User.objects.create(id=id, user_id='pres24', password='Mp!ku*NxX', name='박민우', is_staff='False', tag_search='', cafe_id='')
     user[29] = User.objects.create(id=id, user_id='diana', password='yKHbS^W~A', name='이승재', is_staff='False', tag_search='', cafe_id='')
     user[30] = User.objects.create(id=id, user_id='sted22', password='afWU~jb5G', name='김서원', is_staff='False', tag_search='', cafe_id='')
     user[31] = User.objects.create(id=id, user_id='harran789', password='Yarz_h4Jl', name='이승현', is_staff='False', tag_search='', cafe_id='')
     user[32] = User.objects.create(id=id, user_id='korne64', password='DIXu+^RE3', name='김은서', is_staff='False', tag_search='', cafe_id='')
     user[33] = User.objects.create(id=id, user_id='bridge80', password='WDx5IZ2$?', name='장영희', is_staff='False', tag_search='', cafe_id='')
     user[34] = User.objects.create(id=id, user_id='fola92', password='qhvlNbi?y', name='김여진', is_staff='False', tag_search='', cafe_id='')
     user[35] = User.objects.create(id=id, user_id='ameba35', password='Xhevqf?dK', name='허유진', is_staff='False', tag_search='', cafe_id='')
     user[36] = User.objects.create(id=id, user_id='blankid', password='g1#Rx6^wy', name='이진희', is_staff='False', tag_search='', cafe_id='')
     user[37] = User.objects.create(id=id, user_id='zenn22', password='uhv@Q06AS', name='김경민', is_staff='False', tag_search='', cafe_id='')
     user[38] = User.objects.create(id=id, user_id='sulin758', password='D*ny27^Gc', name='이동욱', is_staff='False', tag_search='', cafe_id='')
     user[39] = User.objects.create(id=id, user_id='tricus', password='a_lQv7XRu', name='김소연', is_staff='False', tag_search='', cafe_id='')
     user[40] = User.objects.create(id=id, user_id='avenda', password='BOzIy?0r$', name='강민경', is_staff='False', tag_search='', cafe_id='')
     user[41] = User.objects.create(id=id, user_id='doyna99', password='o9gloy*yV', name='이명하', is_staff='False', tag_search='', cafe_id='')
     user[42] = User.objects.create(id=id, user_id='cham77', password='WYINX%80z', name='박상현', is_staff='False', tag_search='', cafe_id='')
     user[43] = User.objects.create(id=id, user_id='jenne056', password='Maz-M5L~9', name='위규범', is_staff='False', tag_search='', cafe_id='')
     user[44] = User.objects.create(id=id, user_id='erni32', password='rZdgHsf&u', name='최재영', is_staff='False', tag_search='', cafe_id='')
     user[45] = User.objects.create(id=id, user_id='summo', password='NUWOk*adM', name='김민구', is_staff='False', tag_search='', cafe_id='')
     user[46] = User.objects.create(id=id, user_id='iven38', password='y!tHNnZQe', name='홍만표', is_staff='False', tag_search='', cafe_id='')
     user[47] = User.objects.create(id=id, user_id='beat64', password='Tcz%C@NhA', name='강헌', is_staff='False', tag_search='', cafe_id='')
     user[48] = User.objects.create(id=id, user_id='wine475', password='hw#P*nY1h', name='고정길', is_staff='False', tag_search='', cafe_id='')
     user[49] = User.objects.create(id=id, user_id='rian', password='FHOTlG$Cx', name='오상윤', is_staff='False', tag_search='', cafe_id='')
     user[50] = User.objects.create(id=id, user_id='lita55', password='OIBC~W_vn', name='김수진', is_staff='False', tag_search='', cafe_id='')
     user[51] = User.objects.create(id=id, user_id='tisca853', password='Rzy~2u8Ds', name='한경식', is_staff='False', tag_search='', cafe_id='')
     user[52] = User.objects.create(id=id, user_id='ingo012', password='Zl1?_QtAE', name='임재성', is_staff='False', tag_search='', cafe_id='')
     user[53] = User.objects.create(id=id, user_id='natur80', password='Wu%SA@e46', name='신승훈', is_staff='False', tag_search='', cafe_id='')
     user[54] = User.objects.create(id=id, user_id='tulf25', password='scQN4M@t4', name='김재훈', is_staff='False', tag_search='', cafe_id='')
     user[55] = User.objects.create(id=id, user_id='tabad', password='wuBUfZ$M^', name='송기원', is_staff='False', tag_search='', cafe_id='')
     user[56] = User.objects.create(id=id, user_id='shay73', password='m-Fokoce@', name='신종호', is_staff='False', tag_search='', cafe_id='')
     user[57] = User.objects.create(id=id, user_id='finn29', password='qhHX^mBuB', name='황소영', is_staff='False', tag_search='', cafe_id='')
     user[58] = User.objects.create(id=id, user_id='craft273', password='kGiZ5GV?~', name='김민경', is_staff='False', tag_search='', cafe_id='')
     user[59] = User.objects.create(id=id, user_id='munda', password='Gw48E*uhC', name='장현우', is_staff='False', tag_search='', cafe_id='')
     user[60] = User.objects.create(id=id, user_id='sia222', password='LFDhc4%uq', name='추정현', is_staff='False', tag_search='', cafe_id='')
     user[61] = User.objects.create(id=id, user_id='moria', password='Lo2+t9uiX', name='강동원', is_staff='False', tag_search='', cafe_id='')
     user[62] = User.objects.create(id=id, user_id='sara376', password='u7w%ml^q6', name='서인국', is_staff='False', tag_search='', cafe_id='')
     user[63] = User.objects.create(id=id, user_id='chill965', password='bwRu+HRrh', name='이병헌', is_staff='False', tag_search='', cafe_id='')
     user[64] = User.objects.create(id=id, user_id='naby488', password='RYuWW5?XP', name='이정재', is_staff='False', tag_search='', cafe_id='')
     user[65] = User.objects.create(id=id, user_id='afric576', password='t2PBvE*MY', name='송강호', is_staff='False', tag_search='', cafe_id='')
     user[66] = User.objects.create(id=id, user_id='bree293', password='E7oG*gwIA', name='지창욱', is_staff='False', tag_search='', cafe_id='')
     user[67] = User.objects.create(id=id, user_id='essen00', password='otqHr#co!', name='전소미', is_staff='False', tag_search='', cafe_id='')
     user[68] = User.objects.create(id=id, user_id='brig76', password='X?hekebSX', name='김세정', is_staff='False', tag_search='', cafe_id='')
     user[69] = User.objects.create(id=id, user_id='netta', password='AnPa&UQdw', name='최유정', is_staff='False', tag_search='', cafe_id='')
     user[70] = User.objects.create(id=id, user_id='brita', password='Q&nFoTZw$', name='김도연', is_staff='False', tag_search='', cafe_id='')
     user[71] = User.objects.create(id=id, user_id='amorti33', password='M1CIwo=hk', name='김청하', is_staff='False', tag_search='', cafe_id='')
     user[72] = User.objects.create(id=id, user_id='catha11', password='fJ-av$Rmx', name='송혜교', is_staff='False', tag_search='', cafe_id='')
     user[73] = User.objects.create(id=id, user_id='borne89', password='zYvK8~bcL', name='김태희', is_staff='False', tag_search='', cafe_id='')
     user[74] = User.objects.create(id=id, user_id='moley9292', password='UzwLU*xd-', name='김수현', is_staff='False', tag_search='', cafe_id='')
     user[75] = User.objects.create(id=id, user_id='rihanna', password='viZyAB?G?', name='류준열', is_staff='False', tag_search='', cafe_id='')
     user[76] = User.objects.create(id=id, user_id='camela44', password='UIN7+@ykZ', name='김용선', is_staff='False', tag_search='', cafe_id='')
     user[77] = User.objects.create(id=id, user_id='baron66', password='JkVDATI@i', name='최성희', is_staff='False', tag_search='', cafe_id='')
     user[78] = User.objects.create(id=id, user_id='jessitia', password='UL&tMAO2M', name='이영애', is_staff='False', tag_search='', cafe_id='')
     user[79] = User.objects.create(id=id, user_id='luck88', password='etGGaTKf?', name='최수지', is_staff='False', tag_search='', cafe_id='')
     user[80] = User.objects.create(id=id, user_id='heloku872', password='MqU-aU5bY', name='최홍범', is_staff='False', tag_search='', cafe_id='')
     user[81] = User.objects.create(id=id, user_id='clave830', password='s$ELkgi2*', name='김호용', is_staff='False', tag_search='', cafe_id='')
     user[82] = User.objects.create(id=id, user_id='sarney', password='eAe!!cjWC', name='이기준', is_staff='False', tag_search='', cafe_id='')
     user[83] = User.objects.create(id=id, user_id='colony18', password='KibD?vBaT', name='이웅재', is_staff='True', tag_search='', cafe_id='')
     user[84] = User.objects.create(id=id, user_id='siad153', password='OnnHzC=*A', name='전찬미', is_staff='True', tag_search='', cafe_id='')
     user[85] = User.objects.create(id=id, user_id='inson80', password='tlPyWqd__', name='김보미', is_staff='True', tag_search='', cafe_id='')
     user[86] = User.objects.create(id=id, user_id='cubana', password='DlvGb9$B+', name='전지원', is_staff='True', tag_search='', cafe_id='')
     user[87] = User.objects.create(id=id, user_id='jenith75', password='qasdNM*Pb', name='배현성', is_staff='True', tag_search='', cafe_id='')
     user[88] = User.objects.create(id=id, user_id='belloni', password='JDDFGz$Hb', name='김혜민', is_staff='True', tag_search='', cafe_id='')
     user[89] = User.objects.create(id=id, user_id='adele446', password='xdne%u6?y', name='조유진', is_staff='True', tag_search='', cafe_id='')
     user[90] = User.objects.create(id=id, user_id='aura486', password='hMNcd1D$!', name='이슬기', is_staff='True', tag_search='', cafe_id='')
     user[91] = User.objects.create(id=id, user_id='dorche54', password='vyhPVH_r6', name='김혜빈', is_staff='True', tag_search='', cafe_id='')
     user[92] = User.objects.create(id=id, user_id='everi657', password='xf2Iy&MjL', name='권종구', is_staff='True', tag_search='', cafe_id='')
     user[93] = User.objects.create(id=id, user_id='stocco45', password='j@HbYL=1m', name='곽승은', is_staff='True', tag_search='', cafe_id='')
     user[94] = User.objects.create(id=id, user_id='smish15', password='hvr4s^Q1_', name='한륜희', is_staff='True', tag_search='', cafe_id='')
     user[95] = User.objects.create(id=id, user_id='viran32', password='mpA~c=R1w', name='김수아', is_staff='True', tag_search='', cafe_id='')
     user[96] = User.objects.create(id=id, user_id='rose77', password='nA1z%&Xxp', name='유영웅', is_staff='True', tag_search='', cafe_id='')
     user[97] = User.objects.create(id=id, user_id='domina', password='btU!OPvkf', name='오희진', is_staff='True', tag_search='', cafe_id='')
     user[98] = User.objects.create(id=id, user_id='juan85', password='AEtjKCW_!', name='박주현', is_staff='True', tag_search='', cafe_id='')
     user[99] = User.objects.create(id=id, user_id='malad00', password='zI_KEoW60', name='안윤회', is_staff='True', tag_search='', cafe_id='')
     user[100] = User.object.create(id=id, user_id='gost82', password='jNehon?R6', name='김지환', is_staff='True', tag_search='', cafe_id='')

     for i in range(0,100):
         user[i].save()
'''
     a=User.objects.all()
     return render(request,'leaf/templates/main.html',{'a':a})
'''
def tag_data(request):
     tag[0] = Tag.objects.create(id=id,name='데이트')
     tag[1] = Tag.objects.create(id=id, name='달달')
     tag[2] = Tag.objects.create(id=id, name='디저트카페')
     tag[3] = Tag.objects.create(id=id, name='브런치')
     tag[4] = Tag.objects.create(id=id, name='조용한')
     tag[5] = Tag.objects.create(id=id, name='귀여운')
     tag[6] = Tag.objects.create(id=id, name='책과 함께')
     tag[7] = Tag.objects.create(id=id, name='1인석')
     tag[8] = Tag.objects.create(id=id, name='쇼파')
     tag[9] = Tag.objects.create(id=id, name='와플')
     tag[10] = Tag.objects.create(id=id, name='수제청')
     tag[11] = Tag.objects.create(id=id, name='느낌있는')
     tag[12] = Tag.objects.create(id=id, name='조각케잌')
     tag[13] = Tag.objects.create(id=id, name='예쁜카페')
     tag[14] = Tag.objects.create(id=id, name='포토존')
     tag[15] = Tag.objects.create(id=id, name='분위기있는카페')
     tag[16] = Tag.objects.create(id=id, name='커피가 맛있는')
     tag[17] = Tag.objects.create(id=id, name='유기농')
     tag[18] = Tag.objects.create(id=id, name='테이크아웃')
     tag[19] = Tag.objects.create(id=id, name='테라스')
     tag[20] = Tag.objects.create(id=id, name='힐링카페')
     tag[21] = Tag.objects.create(id=id, name='룸식')
     tag[22] = Tag.objects.create(id=id, name='넓은실내')
     tag[23] = Tag.objects.create(id=id, name='아늑한분위기')
     tag[24] = Tag.objects.create(id=id, name='근사한')
     tag[25] = Tag.objects.create(id=id, name='예약필수')
     tag[26] = Tag.objects.create(id=id, name='다양한음식')
     tag[27] = Tag.objects.create(id=id, name='캠핑분위기')
     tag[28] = Tag.objects.create(id=id, name='높은테이블')
     tag[29] = Tag.objects.create(id=id, name='연중무휴')
     tag[30] = Tag.objects.create(id=id, name='월요일휴무')
     tag[31] = Tag.objects.create(id=id, name='무료주차')
     tag[32] = Tag.objects.create(id=id, name='연인끼리')
     tag[33] = Tag.objects.create(id=id, name='칸막이')
     tag[34] = Tag.objects.create(id=id, name='정원')
     tag[35] = Tag.objects.create(id=id, name='간식')
     tag[36] = Tag.objects.create(id=id, name='착한가격')
     tag[37] = Tag.objects.create(id=id, name='여유로운')
     tag[38] = Tag.objects.create(id=id, name='고급스러운')
     tag[39] = Tag.objects.create(id=id, name='배달가능')
     tag[40] = Tag.objects.create(id=id, name='여자들끼리')
     tag[41] = Tag.objects.create(id=id, name='편한의자')
     tag[42] = Tag.objects.create(id=id, name='혼자카페')
     tag[43] = Tag.objects.create(id=id, name='홈메이드')
     tag[44] = Tag.objects.create(id=id, name='런치세트')
     tag[45] = Tag.objects.create(id=id, name='노키즈')
     tag[46] = Tag.objects.create(id=id, name='모던한분위기')
     tag[47] = Tag.objects.create(id=id, name='넓은테이블')
     tag[48] = Tag.objects.create(id=id, name='아담한 공간')
     tag[49] = Tag.objects.create(id=id, name='자연친화적')
     tag[50] = Tag.objects.create(id=id, name='인스타감성')
     tag[52] = Tag.objects.create(id=id, name='추억돋는')
     tag[53] = Tag.objects.create(id=id, name='세미나장소')
     tag[54] = Tag.objects.create(id=id, name='')
     tag[55] = Tag.objects.create(id=id, name='')
     tag[56] = Tag.objects.create(id=id, name='')
     tag[57] = Tag.objects.create(id=id, name='')
     tag[58] = Tag.objects.create(id=id, name='')
     tag[59] = Tag.objects.create(id=id, name='')
     tag[60] = Tag.objects.create(id=id, name='')
     tag[61] = Tag.objects.create(id=id, name='')
     tag[62] = Tag.objects.create(id=id, name='')
     tag[63] = Tag.objects.create(id=id, name='')
     tag[64] = Tag.objects.create(id=id, name='')
     tag[65] = Tag.objects.create(id=id, name='')
     tag[66] = Tag.objects.create(id=id, name='')
     tag[67] = Tag.objects.create(id=id, name='')
     tag[68] = Tag.objects.create(id=id, name='')
     tag[69] = Tag.objects.create(id=id, name='')
     tag[70] = Tag.objects.create(id=id, name='')
     tag[71] = Tag.objects.create(id=id, name='')
     tag[72] = Tag.objects.create(id=id, name='')
     tag[73] = Tag.objects.create(id=id, name='')
     tag[74] = Tag.objects.create(id=id, name='')
     tag[75] = Tag.objects.create(id=id, name='')
     tag[76] = Tag.objects.create(id=id, name='')
     tag[77] = Tag.objects.create(id=id, name='')
     tag[78] = Tag.objects.create(id=id, name='')
     tag[79] = Tag.objects.create(id=id, name='')
     tag[80] = Tag.objects.create(id=id, name='')
     tag[81] = Tag.objects.create(id=id, name='')
     tag[82] = Tag.objects.create(id=id, name='')
     tag[83] = Tag.objects.create(id=id, name='')
     tag[84] = Tag.objects.create(id=id, name='')
     tag[85] = Tag.objects.create(id=id, name='')
     tag[86] = Tag.objects.create(id=id, name='')
     tag[87] = Tag.objects.create(id=id, name='')
     tag[88] = Tag.objects.create(id=id, name='')
     tag[89] = Tag.objects.create(id=id, name='')
     tag[90] = Tag.objects.create(id=id, name='')
     tag[91] = Tag.objects.create(id=id, name='')
     tag[92] = Tag.objects.create(id=id, name='')
     tag[93] = Tag.objects.create(id=id, name='')
     tag[94] = Tag.objects.create(id=id, name='')
     tag[95] = Tag.objects.create(id=id, name='')
     tag[96] = Tag.objects.create(id=id, name='')
     tag[97] = Tag.objects.create(id=id, name='')
     tag[98] = Tag.objects.create(id=id, name='')
     tag[99] = Tag.objects.create(id=id, name='')
     tag[100] = Tag.objects.create(id=id, name='')
     for i in range(0, 5):
         tag[i].save()
'''
     b = Tag.objects.all()
     return render(request, 'leaf/templates/main.html', {'b':b})
'''

