# Generated by Django 2.0.2 on 2018-05-13 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cafe_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leaf.Cafe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tag_search',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
